name: Build and Release (Windows C++)

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Package binaries
        run: |
          mkdir dist
          copy D:\\a\\ELISE\\ELISE\\build\\Release dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
