name: Build and Release (Windows C++)

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

permissions:
  contents: write


jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Debug Build Directory
        run: |
          dir build\Release
          dir build\ffmpeg\bin

      - name: Package binaries
        run: |
          mkdir dist
          copy build\Release\ELISE.exe dist\ELISE.exe
          copy build\ffmpeg\bin\swscale-9.dll dist\swscale-9.dll
          copy build\ffmpeg\bin\swresample-6.dll dist\swresample-6.dll
          copy build\ffmpeg\bin\avutil-60.dll dist\avutil-60.dll
          copy build\ffmpeg\bin\avformat-62.dll dist\avformat-62.dll
          copy build\ffmpeg\bin\avcodec-62.dll dist\avcodec-62.dll

      - name: Bundle release files into ZIP
        run: Compress-Archive -Path dist\* -DestinationPath ELISE.zip

      - name: Verify ZIP file
        run: |
          if (!(Test-Path -Path ELISE.zip)) {
            Write-Error "Release ZIP file not found!"
            exit 1
          }

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ELISE.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

